name: cse6242_project2
channels:
  - conda-forge
  - defaults
dependencies:
  - ipywidgets
  - jupyterlab
  - pandas
  - geopandas
  - rasterio
  - folium
  - shapely
  - scipy
  - rasterstats
  - jupyterlab_code_formatter
  - black
  - isort
  - ipyleaflet
  - streamlit
  - pip:
    - streamlit_folium